import gradio as gr
import time
import random
from datetime import datetime

def generate_risk_briefing(company_name):
    if not company_name.strip():
        return "Please enter company name or stock code."
    
    time.sleep(1.5)
    
    sentiment = random.choice(["Positive", "Cautiously Optimistic", "Neutral", "Cautious", "Negative"])
    risk = random.choice(["Low", "Medium", "High"])
    events = random.sample(["Supply chain rumors", "Management changes", "Regulatory concerns", "Market volatility", "Earnings expectations"], random.randint(2, 4))
    
    briefing = f"""
## Financial Risk Briefing: **{company_name.upper()}**

**Analysis Time:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Market Sentiment:** {sentiment}
**Overall Risk Level:** **{risk}**

### Recent Focus Points
"""
    for e in events:
        briefing += f"- {e}\n"
    
    briefing += """
---
*Generated by FinRisk-AI-Agents | This is a demo*
"""
    return briefing

# Gradio 4.x 语法
with gr.Blocks() as demo:
    gr.Markdown("# FinRisk-AI-Agents Quick Demo")
    
    with gr.Row():
        input_text = gr.Textbox(label="Enter company name", placeholder="e.g., Tesla")
        submit_btn = gr.Button("Generate Report")
    
    output_text = gr.Textbox(label="Risk Briefing", lines=15)
    
    gr.Examples(
        examples=[["Tesla"], ["Apple"], ["NVIDIA"]],
        inputs=input_text
    )
    
    def generate(text):
        return generate_risk_briefing(text)
    
    submit_btn.click(fn=generate, inputs=input_text, outputs=output_text)

if __name__ == "__main__":
    import os
    import sys
    print("=== Starting FinRisk-AI-Agents Demo ===")
    print(f"Python: {sys.version}")
    print(f"Gradio: {gr.__version__}")
    port = int(os.environ.get("PORT", 7860))
    print(f"Server: http://0.0.0.0:{port}")
    print(f"Local:  http://localhost:{port}")
    print("=" * 40)
    
    # 修改最后一行：
    demo.launch(
    server_name="0.0.0.0",
    server_port=7890,  # 换端口
    share=False
    )