# demo_english.py - English version for deployment
import gradio as gr
import time
import random
from datetime import datetime

def generate_risk_briefing(company_name):
    if not company_name.strip():
        return "Please enter company name or stock code."
    
    time.sleep(1.5)
    
    sentiment = random.choice(["Positive", "Cautiously Optimistic", "Neutral", "Cautious", "Negative"])
    risk = random.choice(["Low", "Medium", "High"])
    events = random.sample(["Supply chain rumors", "Management changes", "Regulatory concerns", "Market volatility", "Earnings expectations"], random.randint(2, 4))
    
    briefing = f"""
## Financial Risk Briefing: **{company_name.upper()}**

**Analysis Time:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Market Sentiment:** {sentiment}
**Overall Risk Level:** **{risk}**

### Recent Focus Points
"""
    for e in events:
        briefing += f"- {e}\n"
    
    briefing += """
---
*Generated by FinRisk-AI-Agents | This is a demo*
"""
    return briefing

demo = gr.Interface(
    fn=generate_risk_briefing,
    inputs=gr.Textbox(label="Enter company name", placeholder="e.g., Tesla"),
    outputs=gr.Textbox(label="Risk Briefing"),
    title="FinRisk-AI-Agents Quick Demo",
    examples=[["Tesla"], ["Apple"], ["NVIDIA"]]
)

if __name__ == "__main__":
    import os
    import sys
    print("=== Starting FinRisk-AI-Agents Demo ===")
    print(f"Python: {sys.version}")
    port = int(os.environ.get("PORT", 7860))
    print(f"Server: http://0.0.0.0:{port}")
    print(f"Local:  http://localhost:{port}")
    print("=" * 40)
    demo.launch(
    server_name="0.0.0.0", 
    server_port=port, 
    share=False, 
    show_error=True,
    headers={"ngrok-skip-browser-warning": "true", "User-Agent": "Mozilla/5.0"}  # 添加这两行
)
